"""add customer validation

Revision ID: 10bf18efae97
Revises: ca514cadf8d0
Create Date: 2026-09-19 02:22:56.238272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bf18efae97'
down_revision: Union[str, Sequence[str], None] = 'ca514cadf8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('participant_type', sa.String(length=100), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('validation_result', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_validations_experiment_id'), 'customer_validations', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_customer_validations_id'), 'customer_validations', ['id'], unique=False)
    op.create_index(op.f('ix_customer_validations_organization_id'), 'customer_validations', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_opportunity_ideas_idea_id'), table_name='opportunity_ideas')
    op.drop_index(op.f('ix_opportunity_ideas_opportunity_id'), table_name='opportunity_ideas')
    op.drop_table('opportunity_ideas')
    op.drop_index(op.f('ix_problem_opportunities_opportunity_id'), table_name='problem_opportunities')
    op.drop_index(op.f('ix_problem_opportunities_problem_id'), table_name='problem_opportunities')
    op.drop_table('problem_opportunities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_opportunities',
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('problem_opportunities_opportunity_id_fkey')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('problem_opportunities_problem_id_fkey')),
    sa.PrimaryKeyConstraint('problem_id', 'opportunity_id', name=op.f('problem_opportunities_pkey'))
    )
    op.create_index(op.f('ix_problem_opportunities_problem_id'), 'problem_opportunities', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_opportunities_opportunity_id'), 'problem_opportunities', ['opportunity_id'], unique=False)
    op.create_table('opportunity_ideas',
    sa.Column('opportunity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('opportunity_ideas_idea_id_fkey')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_ideas_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('opportunity_id', 'idea_id', name=op.f('opportunity_ideas_pkey'))
    )
    op.create_index(op.f('ix_opportunity_ideas_opportunity_id'), 'opportunity_ideas', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_ideas_idea_id'), 'opportunity_ideas', ['idea_id'], unique=False)
    op.drop_index(op.f('ix_customer_validations_organization_id'), table_name='customer_validations')
    op.drop_index(op.f('ix_customer_validations_id'), table_name='customer_validations')
    op.drop_index(op.f('ix_customer_validations_experiment_id'), table_name='customer_validations')
    op.drop_table('customer_validations')
    # ### end Alembic commands ###
